### ISSUE TITLE
Memory leak in slurm_setup_sockaddr

### ISSUE THREAD

**Issue by tack0974** [SchedMD/slurm#121]
Browsing the code, found call to getaddrinfo but not to freeaddrinfo, this would lead to memory leak
in the function, suggestion is to add freeaddrinfo(p_ainfo) just after assigning the result to a local variable
PS: would it make sense to use slurm_set_addr_char instead of getaddrinfo ?

**Comment by davidbigagli** [comment]
Hi, do you have evidence of a leak by using valgrind? If so you can provide a patch for us to check in.

David

**Comment by tack0974** [comment]
No evidence with valgrind, from manpage getattrinfo allocates required memory for result, this memory is allocate dynamically by the function.
patch for existing code is really simple:
@@ -4446,6 +4446,7 @@
 				struct sockaddr_in *p_sin =
 					(struct sockaddr_in *)p_ainfo->ai_addr;
 				s_addr = p_sin->sin_addr.s_addr;
+				freeaddrinfo(p_ainfo);
 			} else
 				fatal("slurm_setup_sockaddr: "
 				      "Can't get hostname or addr: %m");

**Comment by tack0974** [comment]
link to patch 
https://gist.github.com/tack0974/8876eea0eb7f3499ca6c

**Comment by dannyauble** [comment]
I believe this is a correct patch, thanks!  Could you send your contract info so we can add you to the contributors and commit.

I think the reason we didn't use slurm_set_addr_char was because of the extra weight of the call that didn't appear needed.  If you do find a different solution that is as light weight please let us know.
