### ISSUE TITLE
burst_buffer_generic.c: incorrect downcast during calculation of available space

### ISSUE THREAD

**Issue by AndreyNevolin** [SchedMD/slurm#132]
Inside _test_size_limit:

```
402 	add_total_space_needed = bb_state.used_space + add_space + resv_space - 
403 				 bb_state.total_space; 
```

Variable 'add_total_space_needed' is of type 'int'. Expression on the right of the assignment is of type 'uint64_t'.

The cast is incorrect in most cases and results in jobs that hang forever waiting for the resources.

Please fix the issue.

It's better to avoid taking difference at all (because difference of unsigned type variables requires wider signed type; i.e. wider than 64bit in this case).

BTW: when and how generic burst buffer resources are expected to be released? I see that when my job completes - after proper staging-out - Slurm still treats allocated resources as 'used'. And Slurm continues accumulating 'used' resources when I start next job.

**Comment by jette** [comment]
I have no expectation that any of the logic currently in the burst_buffer/generic code works.
Massive changes have been made to support the burst_buffer/cray plugin and all I can say is that does work. The burst_buffer/cray plugin should probably be copied to burst_buffer/generic and modified to use generic scripts rather than the Cray APIs.

**Comment by AndreyNevolin** [comment]
What is an intended future of burst_buffer/generic? Are going to support it or get rid of it?
